apiVersion: v1
kind: Service
metadata:
  name: postgresql
  annotations:
    description: Exposes the database server
  labels:
    app: helpline
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: helpline
    tier: database

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    description: Exposes the redis server
  labels:
    app: helpline
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: helpline
    tier: redis

---

apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: helpline
spec:
  clusterIP: None
  ports:
  - name: web
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: helpline
    tier: api